# These are supported funding model platforms

github: h3pdesign
patreon: h3p
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: h3pdesign
thanks_dev:
custom:
  - https://paypal.me/h3pdesign
  - https://h3p.me
  - https://apps-h3p.com
